baseURL: https://hawkeye-xb.xyz/
title: Hawkeye-xb Blog
paginate: 5
theme: ['PaperMod']

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

defaultContentLanguage: zh
defaultContentLanguageInSubdir: true

services:
  googleAnalytics:
    id: G-QE8H9VMTZ6

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2